### PR TITLE
linux: Makefile: set appropriate permissions on installed files

### PR DESCRIPTION
**Pull request by avoidr**

### CODE REVIEW

**Comment by simon-wh** [comment]
Looks good! Thanks again for these improvements on the Linux makefile. If you've got more in the future I think you could probably group up small ones like this into one

**Comment by avoidr** [comment]
Thanks!

Okay, I will! I had done it that way because I like to keep things separate by feature. But yes, they were very minimal :P
I'll still have more patches later ☺

By the way; my Linux Makefile changes can probably all be transferred to the MacOS Makefile. But I didn't do it because I don't have a Mac to test it on. Shall I make a PR for MacOS Makefile?

**Comment by simon-wh** [comment]
> By the way; my Linux Makefile changes can probably all be transferred to the MacOS Makefile. But I didn't do it because I don't have a Mac to test it on. Shall I make a PR for MacOS Makefile?

I don't have a Mac so I'm not certain, but I think all the changes you've made should be suitable for porting over to the Mac makefile(?)

**Comment by avoidr** [comment]
I think so. I think MacOS users probably use the GNU implementation of make, so everything should be the same so far. Except system details. I'll make a PR.

**Pull request merged**
