### PR TITLE
linux: Makefile: add CPPFLAGS variable

### PR DESCRIPTION
**Pull request by avoidr**
This allows to set DEBUG_LOG from shell.

### CODE REVIEW

**Comment by burito** [comment]
CPPFLAGS is for C++, the appropriate C variable is CFLAGS

**Comment by avoidr** [comment]
`CPPFLAGS` is for the C preprocessor.
`CXXFLAGS` is to C++ what `CFLAGS` is to C.

https://www.gnu.org/software/make/manual/html_node/Implicit-Variables.html

**Comment by simon-wh** [comment]
Thank you! Those changes make a lot of sense, we're going to update the readme slightly to mention the ability to add the flag to get a bit of debug logging.

**Comment by avoidr** [comment]
Awesome, thanks! :)

**Pull request merged**
